changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Bugfixes
      labels:
        - bug
    - title: New Features
      labels:
        - new feature
    - title: Other Changes
      labels:
        - "*"
