name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: [ "bug", "triage" ]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: what-should-have-happened
    attributes:
      label: What should have happened?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce the issue
      value:
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      placeholder: Page URL, screenshot, video recording, etc
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Live
        - Beta
      default: 0
    validations:
      required: true

  - type: dropdown
    id: theme
    attributes:
      label: Theme
      options:
        - Customer
        - Admin
      default: 0
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: "Iphone 10, Desktop, etc."
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Edge
        - Firefox
