name: Deployment

on: [release]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://app.com
    steps:
      - name: deploy
        run: echo "deploy"
