name: Javascript code quality

on: [ push, pull_request ]
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install packages
        run: npm install
      - name: ESLint
        run: npx eslint