name: PHP code quality
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    name: PHP code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
          tools: composer

      - name: Install composer packages
        run: composer install

      - name: Run php-cs-fixer
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
        run: vendor/bin/php-cs-fixer check

      - name: Run PHPStan
        run: vendor/bin/phpstan --error-format=github